name: Broken link
description: Report a broken or outdated link.
labels: ["bug"]
body:
  - type: input
    id: page
    attributes:
      label: Page URL
    validations:
      required: true
  - type: input
    id: broken
    attributes:
      label: Broken link
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What did you expect?
    validations:
      required: false
